# Generated by Django 5.0.6 on 2024-06-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='cassette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecassete', models.CharField(max_length=50)),
                ('preciocassete', models.IntegerField()),
                ('descripcioncassete', models.TextField()),
                ('nuevocassete', models.BooleanField()),
                ('fecha_lanzamientocassete', models.DateField()),
                ('imagencassete', models.ImageField(null=True, upload_to='cassettes')),
            ],
        ),
        migrations.CreateModel(
            name='cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecd', models.CharField(max_length=50)),
                ('preciocd', models.IntegerField()),
                ('descripcioncd', models.TextField()),
                ('nuevocd', models.BooleanField()),
                ('fecha_lanzamientocd', models.DateField()),
                ('imagencd', models.ImageField(null=True, upload_to='cds')),
            ],
        ),
        migrations.CreateModel(
            name='vinilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('nuevo', models.BooleanField()),
                ('fecha_lanzamiento', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='vinilos')),
            ],
        ),
        migrations.DeleteModel(
            name='producto',
        ),
    ]
