# Generated by Django 5.0.6 on 2024-06-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_cassette_cd_vinilo_delete_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cassette',
            old_name='descripcioncassete',
            new_name='descripcion_cassete',
        ),
        migrations.RenameField(
            model_name='cassette',
            old_name='fecha_lanzamientocassete',
            new_name='fecha_lanzamiento_cassete',
        ),
        migrations.RenameField(
            model_name='cassette',
            old_name='imagencassete',
            new_name='imagen_cassete',
        ),
        migrations.RenameField(
            model_name='cassette',
            old_name='nombrecassete',
            new_name='nombre_cassete',
        ),
        migrations.RenameField(
            model_name='cassette',
            old_name='nuevocassete',
            new_name='nuevo_cassete',
        ),
        migrations.RenameField(
            model_name='cassette',
            old_name='preciocassete',
            new_name='precio_cassete',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='descripcioncd',
            new_name='descripcion_cd',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='fecha_lanzamientocd',
            new_name='fecha_lanzamiento_cd',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='imagencd',
            new_name='imagen_cd',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='nombrecd',
            new_name='nombre_cd',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='nuevocd',
            new_name='nuevo_cd',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='preciocd',
            new_name='precio_cd',
        ),
    ]
